apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-helm-app.fullname" . }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        version: {{ .Values.application.version }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image }}
          ports:
            - containerPort: 8080